apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-internal
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    nodePort: 30080
  - name: https
    port: 443
    protocol: HTTPS
    nodePort: 30443
