apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: redis
    targetRevision: 25.3.0
    helm:
      releaseName: "redis"
      valuesObject:
        global:
          defaultStorageClass: nfs-client
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
