apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-insight
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://heywood8.github.io/helm-charts
    chart: redisinsight
    targetRevision: 0.4.5
    helm:
      releaseName: redis-insight
      valuesObject:
        persistentVolumeClaim:
          storageClassName: nfs-client
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
