apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-insight
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/m1dugh/infrastructure.git
    targetRevision: HEAD
    path: apps/redis-insight
  destination:
    server: https://kubernetes.default.svc
    namespace: infrastructure
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
